[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "argshell"
description = "Integrates the argparse and cmd modules."
version = "1.2.0"
requires-python = ">=3.10"
dependencies = ["pytest"]
readme = "README.md"
keywords = ["argparse", "cmd", "shell", "commandline", "terminal"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    ]

[[project.authors]]
name = "Matt Manes"
email = "mattmanes@pm.me"

[project.urls]
"Homepage" = "https://github.com/matt-manes/argshell"
"Documentation" = "https://github.com/matt-manes/argshell/tree/main/docs"
"Source code" = "https://github.com/matt-manes/argshell/tree/main/src/argshell"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    ]
pythonpath = "src"

[tool.hatch.build.targets.sdist]
exclude = [
    ".coverage",
    ".pytest_cache",
    ".vscode",
    "tests",
    ".gitignore"
    ]

