[build-system]
requires = ["setuptools>=67.7.2", "wheel"]

[project]
name = "retention-rules"
version = "0.1.1"
authors = [
    {name = "Matt Jarvis"},
]
description = "A library to calculate period-based retention rules for timestamps"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]

[project.urls]
"Homepage" = "https://github.com/mattj23/retention-rules"