[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "moneycounter"
description = "Portfolio Analytics Utilities"
readme = "README.md"
authors = [ {name="Marc Schwarzschild", email="ms@TheBrookhavenGroup.com"}, ]
maintainers = [ {name="Marc Schwarzschild", email="ms@TheBrookhavenGroup.com"}, ]
requires-python = ">=3.7"
keywords = ["risk", "fifo", "money", "investments"]
classifiers = [
    "Topic :: Office/Business :: Financial",
    "Topic :: Office/Business :: Financial :: Accounting",
    "Topic :: Office/Business :: Financial :: Investment"
    ]
license = {text = "MIT"}
dependencies = ["pandas==1.5.2", "pytz==2022.7"]
version = "1.3.1"

[project.urls]
homepage = "https://github.com/schwarzschild/moneycounter"
repository = "https://github.com/schwarzschild/moneycounter"
documentation = "https://github.com/schwarzschild/moneycounter"
