[tool.poetry]
name = "simplepg"
version = "0.1.4"
description = "Simple PostgreSQL connections"
authors = ["Mysterious Ben <datascience@tuta.io>"]
exclude = [".git", ".gitignore", ".venv/", ".mypy_cache/", "__pycache__", ".eggs/"]
license = "Apache License 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
psycopg2 = "^2.9.5"
loguru = "^0.5.0"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
isort = "^5.11.4"
mypy = "^0.991"
pytest = "^7.2.0"
pylint = "^2.15.9"
flake8 = "^6.0.0"
python-dotenv = "^1.0.0"
envparse = "^0.2.0"
pre-commit = "^3.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line_length = 99
target_version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.github
    | \.mypy_cache
    | \.tox
    | \.venv
    | \notebooks
    | .ipynb_checkpoints
    | __pycache__
    | _build
    | build
    | dist
    | \.venv
  )/
)
'''

[tool.pytest.ini_options]
markers = [
    "integration: integration testing (tests require valid credentials and can be slow)",
]
testpaths = [
    "tests",
]
