[tool.poetry]
name = "morgan-linter"
version = "1.2.1"
description = "Linter to validate google docstrings"
authors = ["Edwar Gir√≥n <contactoedwargiron@gmail.com>"]
readme = "README.md"
packages = [{include = "morgan_linter"}]

[tool.poetry.dependencies]
python = ">=3.8.*"


[tool.poetry.group.testing.dependencies]
pytest = "^7.2.0"

[tool.poetry.scripts]
morgan = "morgan_linter:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

