[tool.poetry]
name = "ou-tm351-jl-extensions"
version = "0.1.0"
description = ""
authors = ["Tony Hirst <tony.hirst@gmail.com>"]
readme = "README.md"
packages = [{include = "ou_tm351_jl_extensions"}]

[tool.poetry.dependencies]
python = "^3.11"
jupyterlab-ou-brand-extension = "^0.1.0"
jupyterlab-cell-status-extension = "^0.1.3"
jupyterlab-myst = "^1.1.3"
jupyterlab-empinken-extension = "^0.1.1"
jupyterlab-geojson = "^3.3.1"
jupyterlab-skip-traceback = "^4.0.4"
jupyterlab-git = "^0.41.0"
jupytext = "^1.14.5"
jupyter-archive = "^3.3.4"
jupyterlab-spellchecker = "^0.7.3"
jupyterlab-language-pack-fr-fr = "^3.6.post1"
jupyterlab-language-pack-zh-cn = "^3.6.post1"
jupyter-resource-usage = "^0.7.2"
stickyland = "^0.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
