[tool.poetry]
name = "graphcol"
version = "0.4.2"
description = ""
authors = ["WLAraujo <lima.wesleyaraujo@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
igraph = "^0.9.9"
cairocffi = "^1.3.0"
numpy = "^1.23.0"
matplotlib = "^3.6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[[tool.poetry.source]]
name = "graphcol"
url = "https://pypi.org/project/graphcol/"
default = false
secondary = false

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
