[tool.poetry]
name = "malla"
version = "0.1.5"
description = ""
authors = ["Dimas Mart√≠nez <dimas@ufam.edu.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
